FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY api/*.csproj ./
RUN dotnet restore

COPY api/. ./

RUN dotnet build -c Release -o /app/build

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/build .
EXPOSE 80
ENTRYPOINT ["dotnet", "YourApiAssemblyName.dll"]
