services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: yunus-web
    volumes:
      - /app
    ports:
      - "2801:2801"
    # depends_on:
    #   - apidock

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #   container_name: dotnet_api
  #   ports:
  #     - "5000:80"
  #   volumes:
  #     - ./api:/app
  #   working_dir: /app
  #   command: sh -c "dotnet restore && dotnet build && dotnet run --urls=http://0.0.0.0:80"
  #   depends_on:
  #     - db

  # db:
  #   image: mcr.microsoft.com/mssql/server:latest
  #   container_name: sql_server
  #   environment:
  #     SA_PASSWORD: "YourStrong@Passw0rd"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlserverdata:/var/opt/mssql

# volumes:
#   sqlserverdata:
