# Base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install pnpm and dependencies
RUN npm install -g pnpm && pnpm install

# Copy application files
COPY . .

# Expose port
EXPOSE 5173

# Start the application
CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]
